name: Update changelog on release published

on:
  release:
    types: [published]

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Update changelog from release
        uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_summary_template: "chore: update changelog for %s"
          header: |
            <style>
              h1:first-of-type {
                  display: none;
              }
              .my-5 {
                  margin: unset !important;
              }
              .markdown-body img {
                 max-width: 50%;
              }
              
              @media (prefers-color-scheme: dark) {
                  body {
                      color-scheme: dark;
                      color: white;
                      background: transparent;
                  }
                  a, :link {
                      color: #419cff;
                  }
                  a:active, link:active {
                      color: #ff1919;
                  }
              }
            </style>

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${{ github.event.release.tag_name }}"
          git push --force "https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/${{ github.repository }}.git"
